name: Terraform Deploy - Stage

on:
  push:
    branches:
      - stage

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Stage deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::269825205299:role/GitHubActions-Terraform-Stage
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Show repo and working-dir
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          pwd
          ls -la

      - name: Terraform Init (Stage)
        working-directory: ./environments/stage
        run: terraform init -input=false

      - name: Terraform Validate (Stage)
        working-directory: ./environments/stage
        run: terraform validate

      - name: Terraform Plan (Stage)
        working-directory: ./environments/stage
        run: terraform plan -out=/tmp/stage-tfplan -input=false

      - name: Terraform Show Plan
        run: terraform show -no-color /tmp/stage-tfplan || true

      - name: Terraform Apply (Stage)
        working-directory: ./environments/stage
        run: terraform apply -input=false /tmp/stage-tfplan
